services:
  db:
    env_file: .env
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/doctors-appointment
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  app_webpack:
    build: .
    command: bundle exec ./bin/webpack-dev-server
    volumes:
      - ./:/webpack-dev-server
    ports:
      - "3035:3035"
    depends_on:
      - web