version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  kubernetes: circleci/kubernetes@0.10.0
  aws-cli: circleci/aws-cli@1.3.0
  slack: circleci/slack@4.1.1

default_environment: &default_environment
  working_directory: ~/DOCTORS_APPOINTMENT
  docker:
    - image: cimg/ruby:3.0.3
      environment:
        BUNDLE_JOBS: 4
        BUNDLE_PATH: vendor/bundle
        BUNDLE_RETRY: 3
        BUNDLE_WITHOUT: development:staging:production
        BUNDLE_WITH: test
        DB_HOST: localhost
        PGHOST: 127.0.0.1
        RAILS_ENV: test
        REDIS_HOST: 127.0.0.1
    - image: circleci/postgres:12.0-alpine
      environment:
        POSTGRES_DB: doctors_appointment_test
        POSTGRES_PASSWORD: ""
        POSTGRES_USER: circleci
    - image: redis
