CALENDLY_BASE_URL = ENV['CALENDLY_BASE_URL'] || 'https://api.calendly.com'
CALENDLY_API_TOKEN = ENV['CALENDLY_API_TOKEN'] || 'eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ'
CALENDLY_ORGANIZATION_UUID = ENV['CALENDLY_ORGANIZATION_UUID'] || '4a71b2dd-c5c2-46e9-9e75-c3e528433f4c'
